services:
  wg-easy:
    pull_policy: always
    environment:
      ACCESS_TOKEN: "{{ INSTANCE_TOKEN }}"
      POST_STATE_URL: "{{ POST_STATE_URL }}"
      POST_CONFIG_DATA_URL: "{{ POST_CONFIG_DATA_URL }}"
      WG_HOST: "{{ host }}"
      PASSWORD_HASH: "{{ hashed_password }}"
    image: ghcr.io/support-pl/wireguard-agent:latest
    container_name: "{{ cont_name }}"
    volumes:
      - "{{ cfg_dir }}/:/etc/wireguard/"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1