name: Delete old container images

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cleanup Untagged Images (> 1 day)
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: support-pl/wireguard-agent
          cut-off: A day ago UTC
          account-type: org
          org-name: Support-pl
          untagged-only: true
          token: ${{ secrets.PACKAGES_PAT }}
